/**
 * Seed Material Universe – real retail dimensions from public sources.
 * Expandable. Later: user uploads, community, or product APIs.
 */

import type { CatalogItem } from "./types";

export const FORGE_CATALOG: CatalogItem[] = [
  {
    id: "popsicle-standard",
    name: "Standard Popsicle Stick",
    brand: "Generic / Craft",
    category: "craft_wood",
    formFactor: "stick",
    dims: { length: 4.5, width: 0.375, thickness: 0.08 },
    unitsPerPack: 100,
    unitCostUsd: 0.03,
    aliases: ["popsicle stick", "craft stick", "ice cream stick", "tongue depressor small"],
    tags: ["wood", "craft", "kids", "model"],
    preferredJoins: ["glue", "notch"],
    canCut: true,
    color: "#e8d5a3",
    roughness: 0.65,
    searchQuery: "standard 4.5 inch popsicle sticks bulk",
    notes: "Most common craft stick. Birch. ±1mm variance typical.",
  },
  {
    id: "wire-frame",
    name: "Wire frame (pick a stock)",
    category: "other",
    formFactor: "dowel",
    dims: { length: 48, diameter: 0.06 },
    unitsPerPack: 1,
    unitCostUsd: 0,
    aliases: ["wire", "wireframe", "skeleton", "outline"],
    tags: ["wire", "placeholder", "choose-stock"],
    preferredJoins: ["none"],
    canCut: true,
    color: "#a8a296",
    roughness: 0.35,
    metalness: 0.2,
    searchQuery: "",
    notes: "Placeholder skeleton only. Open Stock and pick a real material to densify the form.",
  },
  {
    id: "popsicle-jumbo",
    name: "Jumbo Craft Stick",
    brand: "Generic",
    category: "craft_wood",
    formFactor: "stick",
    dims: { length: 6, width: 0.75, thickness: 0.08 },
    unitsPerPack: 50,
    unitCostUsd: 0.06,
    aliases: ["jumbo popsicle", "large craft stick", "tongue depressor"],
    tags: ["wood", "craft", "stronger"],
    preferredJoins: ["glue", "notch", "screw"],
    canCut: true,
    color: "#e0c990",
    roughness: 0.65,
    searchQuery: "jumbo craft sticks 6 inch",
  },
  {
    id: "popsicle-mini",
    name: "Mini Craft Stick",
    category: "craft_wood",
    formFactor: "stick",
    dims: { length: 2.5, width: 0.25, thickness: 0.06 },
    unitsPerPack: 200,
    unitCostUsd: 0.015,
    aliases: ["mini popsicle", "small craft stick"],
    tags: ["wood", "detail", "miniature"],
    preferredJoins: ["glue"],
    canCut: true,
    color: "#f0e0b8",
    searchQuery: "mini craft sticks 2.5 inch",
  },
  {
    id: "popsicle-giant",
    name: "Giant Craft Stick",
    category: "craft_wood",
    formFactor: "stick",
    dims: { length: 12, width: 0.75, thickness: 0.12 },
    unitsPerPack: 25,
    unitCostUsd: 0.25,
    aliases: ["giant popsicle stick", "12 inch craft stick"],
    tags: ["wood", "structure", "architecture model"],
    preferredJoins: ["glue", "notch", "screw"],
    canCut: true,
    color: "#d4b87a",
    searchQuery: "giant craft sticks 12 inch",
  },
  {
    id: "bamboo-skewer-12",
    name: "Bamboo Skewer 12\"",
    category: "craft_wood",
    formFactor: "dowel",
    dims: { length: 12, diameter: 0.125 },
    unitsPerPack: 100,
    unitCostUsd: 0.02,
    aliases: ["skewer", "bamboo stick", "kebab stick"],
    tags: ["bamboo", "thin", "pin"],
    preferredJoins: ["glue", "friction", "pin"],
    canCut: true,
    color: "#c9a86c",
    searchQuery: "bamboo skewers 12 inch",
  },
  {
    id: "straw-plastic",
    name: "Plastic Drinking Straw",
    category: "plastic",
    formFactor: "tube",
    dims: { length: 7.75, diameter: 0.25, innerDiameter: 0.2 },
    unitsPerPack: 100,
    unitCostUsd: 0.02,
    aliases: ["straw", "drinking straw", "plastic straw"],
    tags: ["plastic", "kids", "lightweight"],
    preferredJoins: ["tape", "glue", "friction"],
    canCut: true,
    color: "#f0f0f0",
    roughness: 0.3,
    searchQuery: "plastic drinking straws bulk",
  },
  {
    id: "pvc-3-4-sch40",
    name: '3/4\" Schedule 40 PVC Pipe',
    category: "pvc_plumbing",
    formFactor: "pipe",
    dims: { length: 120, diameter: 1.05, innerDiameter: 0.804 },
    unitsPerPack: 1,
    unitCostUsd: 6.0,
    aliases: ["3/4 PVC", "three quarter PVC", "pvc"],
    tags: ["pvc", "structure"],
    preferredJoins: ["solvent", "friction"],
    canCut: true,
    color: "#f0f0eb",
    searchQuery: "3/4 inch schedule 40 PVC pipe",
  },
  {
    id: "lumber-1x4-8",
    name: "1×4 Board (8 ft)",
    category: "lumber",
    formFactor: "board",
    dims: { length: 96, width: 3.5, height: 0.75 },
    unitsPerPack: 1,
    unitCostUsd: 4.0,
    aliases: ["1x4", "one by four"],
    tags: ["lumber", "trim", "shelf"],
    preferredJoins: ["screw", "nail", "glue"],
    canCut: true,
    color: "#e0d0b0",
    searchQuery: "1x4x8 pine board",
  },
  {
    id: "lumber-2x4-8",
    name: "2×4 Stud (8 ft)",
    brand: "Generic SPF / Douglas Fir",
    category: "lumber",
    formFactor: "board",
    dims: { length: 96, width: 3.5, height: 1.5 },
    unitsPerPack: 1,
    unitCostUsd: 5.5,
    aliases: ["2x4", "two by four", "stud"],
    tags: ["lumber", "framing", "structure"],
    preferredJoins: ["screw", "nail", "glue"],
    canCut: true,
    color: "#d8c4a0",
    roughness: 0.75,
    searchQuery: "2x4x8 stud",
  },
  {
    id: "lumber-2x2-8",
    name: "2×2 (8 ft)",
    category: "lumber",
    formFactor: "board",
    dims: { length: 96, width: 1.5, height: 1.5 },
    unitsPerPack: 1,
    unitCostUsd: 4.5,
    aliases: ["2x2", "two by two", "table leg"],
    tags: ["lumber", "leg", "furniture"],
    preferredJoins: ["screw", "glue"],
    canCut: true,
    color: "#dcc8a0",
    roughness: 0.72,
    searchQuery: "2x2x8 pine poplar",
  },
  {
    id: "plywood-3-4-4x8",
    name: '3/4\" Plywood 4×8',
    category: "sheet_goods",
    formFactor: "sheet",
    dims: { length: 96, width: 48, thickness: 0.75 },
    unitsPerPack: 1,
    unitCostUsd: 55,
    aliases: ["3/4 plywood", "cabinet plywood", "plywood"],
    tags: ["sheet", "cabinet", "furniture"],
    preferredJoins: ["screw", "glue", "notch"],
    canCut: true,
    color: "#d4a574",
    roughness: 0.65,
    searchQuery: "3/4 inch 4x8 plywood",
  },
  {
    id: "toothpick",
    name: "Wooden Toothpick",
    category: "craft_wood",
    formFactor: "stick",
    dims: { length: 2.5, width: 0.08, thickness: 0.08 },
    unitsPerPack: 250,
    unitCostUsd: 0.005,
    aliases: ["toothpick", "wood toothpick"],
    tags: ["tiny", "detail", "model"],
    preferredJoins: ["glue"],
    canCut: true,
    color: "#f5e6c8",
    roughness: 0.6,
    searchQuery: "wooden toothpicks",
  },
  {
    id: "paper-towel-roll",
    name: "Paper Towel Roll Core",
    category: "paper_tube",
    formFactor: "tube",
    dims: { length: 11, diameter: 1.5, innerDiameter: 1.4 },
    unitsPerPack: 1,
    unitCostUsd: 0.0,
    aliases: ["paper towel tube", "kitchen roll core"],
    tags: ["cardboard", "recycled", "tube"],
    preferredJoins: ["glue", "tape", "slot", "friction"],
    canCut: true,
    color: "#d4c4a8",
    roughness: 0.85,
    searchQuery: "empty paper towel rolls craft",
  },
  {
    id: "dowel-1-4-36",
    name: '1/4\" Hardwood Dowel 36\"',
    category: "dowel_rod",
    formFactor: "dowel",
    dims: { length: 36, diameter: 0.25 },
    unitsPerPack: 1,
    unitCostUsd: 1.2,
    aliases: ["quarter inch dowel", "1/4 dowel rod", "dowel"],
    tags: ["wood", "round", "pin"],
    preferredJoins: ["glue", "friction", "pin"],
    canCut: true,
    color: "#d4b896",
    searchQuery: "1/4 inch hardwood dowel 36 inch",
  },
  {
    id: "glue",
    name: "Wood glue",
    category: "hardware",
    formFactor: "block",
    dims: { length: 4, width: 2, height: 7 },
    unitsPerPack: 1,
    unitCostUsd: 5,
    aliases: ["titebond", "craft glue", "wood glue"],
    tags: ["binder", "glue"],
    preferredJoins: ["glue"],
    canCut: false,
    color: "#c45c4a",
    searchQuery: "titebond wood glue 8 oz",
  },
];

export const CATALOG_BY_ID: Record<string, CatalogItem> = Object.fromEntries(
  FORGE_CATALOG.map((item) => [item.id, item])
);

export const CATALOG_CATEGORIES: { id: CatalogItem["category"]; label: string }[] = [
  { id: "craft_wood", label: "Craft Sticks & Wood" },
  { id: "paper_tube", label: "Paper & Cardboard Tubes" },
  { id: "pvc_plumbing", label: "PVC Pipe" },
  { id: "dowel_rod", label: "Dowels & Rods" },
  { id: "lumber", label: "Dimensional Lumber" },
  { id: "sheet_goods", label: "Sheet Goods" },
  { id: "foam", label: "Foam & Model" },
  { id: "cardboard", label: "Cardboard" },
  { id: "metal", label: "Metal" },
  { id: "plastic", label: "Plastic" },
  { id: "recycled", label: "Recycled / Free" },
  { id: "hardware", label: "Hardware" },
  { id: "other", label: "Other" },
];

export function searchCatalog(query: string, limit = 40): CatalogItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return FORGE_CATALOG.slice(0, limit);
  const scored = FORGE_CATALOG.map((item) => {
    let score = 0;
    const name = item.name.toLowerCase();
    const aliases = (item.aliases ?? []).map((a) => a.toLowerCase());
    const tags = (item.tags ?? []).map((t) => t.toLowerCase());
    if (name === q) score += 100;
    else if (name.startsWith(q)) score += 60;
    else if (name.includes(q)) score += 30;
    for (const a of aliases) {
      if (a === q) score += 90;
      else if (a.startsWith(q)) score += 50;
      else if (a.includes(q)) score += 20;
    }
    for (const t of tags) {
      if (t === q || t.startsWith(q)) score += 15;
    }
    return { item, score };
  });
  return scored.filter((s) => s.score > 0).sort((a, b) => b.score - a.score).slice(0, limit).map((s) => s.item);
}

export function getCatalogItem(id: string): CatalogItem | undefined {
  return CATALOG_BY_ID[id];
}
