import { POCKET_SHORT } from "./pocket";

export type IdeaGroup = "house" | "weekend";

export type Idea = {
  id: string;
  group: IdeaGroup;
  section: string;
  label: string;
  size: string;
  prompt: string;
  blurb: string;
  /** Named stock for weekend cards — not a photo. */
  stock?: string;
};

/** Honest prompts only — walked on yard.wiki. Each tap fills the prompt bar. */
export const IDEAS: Idea[] = [
  {
    id: "pocket",
    group: "house",
    section: "Fitted to a hole",
    label: "Pocket vanity",
    size: "38 × 102 × 17",
    prompt: POCKET_SHORT,
    blurb: "Knee, drawers, uppers — the unit the pocket actually holds.",
  },
  {
    id: "linen",
    group: "house",
    section: "Fitted to a hole",
    label: "Linen closet",
    size: "31.5 × 78 × 16",
    prompt: "linen closet for a 31.5 inch bathroom alcove, 78 tall, 16 deep",
    blurb: "The alcove you typed is the unit you get.",
  },
  {
    id: "closet80",
    group: "house",
    section: "Fitted to a hole",
    label: "Closet system",
    size: "80 × 120 × 24",
    prompt: "closet system 80x120",
    blurb: "Three bays, hanging rod, doors. Width then height.",
  },
  {
    id: "window",
    group: "house",
    section: "Fitted to a hole",
    label: "Andersen hung",
    size: "36 × 48",
    prompt: "Andersen 100 Series 36 by 48 double hung window, frame the rough opening",
    blurb: "Pick the unit. Frame its RO. Buy the window and the lumber.",
  },
  {
    id: "desk",
    group: "house",
    section: "Sit and work",
    label: "Desk",
    size: "60 × 30 × 29 · 24″ knee",
    prompt: "desk 60 inches wide by 30 deep by 29 high with drawers and 24 inch knee space",
    blurb: "Drawers and a place to sit.",
  },
  {
    id: "island",
    group: "house",
    section: "Sit and work",
    label: "Kitchen island",
    size: "60 × 36 × 36",
    prompt: "kitchen island 60x36x36",
    blurb: "Open both sides, counter, toekick. Not a cabinet with a back.",
  },
  {
    id: "bench",
    group: "house",
    section: "Sit and work",
    label: "Mudroom bench",
    size: "48 × 18 × 16",
    prompt: "mudroom bench 48 wide 18 high 16 deep",
    blurb: "Seat, shoe cubbies, front apron. Sit on it.",
  },
  {
    id: "headboard",
    group: "house",
    section: "Sit and work",
    label: "Headboard",
    size: "60 wide",
    prompt: "headboard 60 wide",
    blurb: "One slab. Not a box.",
  },
  {
    id: "laundry",
    group: "house",
    section: "Sit and work",
    label: "Laundry folding table",
    size: "48 × 36 × 24",
    prompt: "laundry folding table 48 wide 36 high 24 deep",
    blurb: "Plywood top, four legs, perimeter rails. Height is 36.",
  },
  {
    id: "round",
    group: "house",
    section: "Sit and work",
    label: "Round 3-leg table",
    size: "40″ round",
    prompt: "40 inch round 3-leg table",
    blurb: "Actually round. Aprons span post to post.",
  },
  {
    id: "coffee",
    group: "house",
    section: "Sit and work",
    label: "Coffee table",
    size: "48″ round × 18 high",
    prompt: "coffee table 48 round",
    blurb: "Coffee height, not dining height.",
  },
  {
    id: "shelves",
    group: "house",
    section: "Hang on the wall",
    label: "Floating shelves",
    size: "36 × 10",
    prompt: "floating shelves 36 wide 10 deep",
    blurb: "Boards on wall cleats. Lags into studs.",
  },
  {
    id: "coat",
    group: "house",
    section: "Hang on the wall",
    label: "Coat rack",
    size: "36 × 12 × 4",
    prompt: "coat rack 36 wide 12 high 4 deep",
    blurb: "Peg rail and a hat shelf. The numbers you type stick.",
  },
  {
    id: "spice",
    group: "house",
    section: "Hang on the wall",
    label: "Spice rack",
    size: "18 × 24 × 4",
    prompt: "spice rack 18 wide 24 high 4 deep",
    blurb: "Wall-hung. Fixed shelves with jar lips.",
  },
  {
    id: "wine",
    group: "house",
    section: "Hang on the wall",
    label: "Wine rack",
    size: "24 × 36 × 12",
    prompt: "wine rack 24 wide 36 high 12 deep",
    blurb: "Bottle rails so they don’t roll. Lags into studs.",
  },
  {
    id: "medicine",
    group: "house",
    section: "Hang on the wall",
    label: "Medicine cabinet",
    size: "16 × 24 × 4",
    prompt: "bathroom medicine cabinet 16 wide 24 high 4 deep",
    blurb: "Hung mirrored box. Not a floor vanity.",
  },
  {
    id: "ironing",
    group: "house",
    section: "Hang on the wall",
    label: "Ironing cabinet",
    size: "16 × 48 × 6",
    prompt: "wall mounted ironing board cabinet 48 high 16 wide 6 deep",
    blurb: "Fold-down board, overlay door, support leg.",
  },
  {
    id: "hood",
    group: "house",
    section: "Hang on the wall",
    label: "Range hood",
    size: "30 × 24 × 18",
    prompt: "30 inch range hood",
    blurb: "Plywood canopy and chimney. Not a wire skeleton.",
  },
  {
    id: "tv",
    group: "house",
    section: "Store",
    label: "TV console",
    size: "70 × 30 × 16",
    prompt: "TV console 70 wide 30 tall 16 deep",
    blurb: "Three open bays, shelves, toekick. No leftover doors.",
  },
  {
    id: "dresser",
    group: "house",
    section: "Store",
    label: "Dresser",
    size: "60 × 36 × 18",
    prompt: "dresser 60 wide",
    blurb: "Drawers on slides. Not table legs.",
  },
  {
    id: "nightstand",
    group: "house",
    section: "Store",
    label: "Nightstand",
    size: "18 × 24 × 16",
    prompt: "nightstand 18 wide",
    blurb: "One drawer and an open shelf. Bedside, not a mini dresser.",
  },
  {
    id: "overtoilet",
    group: "house",
    section: "Store",
    label: "Over-toilet",
    size: "27 × 68 × 9",
    prompt: "over the toilet cabinet 27 wide 68 high 9 deep",
    blurb: "Open bottom over the tank. Shelves above.",
  },
  {
    id: "crate",
    group: "house",
    section: "Store",
    label: "Dog crate",
    size: "36 × 30 × 24",
    prompt: "dog crate 36 wide",
    blurb: "Wooden kennel with a hinged door. Not a bookcase.",
  },
  {
    id: "eiffel",
    group: "weekend",
    section: "Weekend",
    label: "Popsicle Eiffel",
    size: "3 ft",
    prompt: "3 foot Eiffel Tower from popsicle sticks",
    blurb: "Four arches, four piers, one shaft. Real sticks, the height you typed.",
    stock: "from popsicle sticks",
  },
  {
    id: "arch",
    group: "weekend",
    section: "Weekend",
    label: "PVC garden arch",
    size: "6 ft",
    prompt: "6 foot garden arch from 3/4 inch PVC pipe",
    blurb: "Walk-through portal from Schedule 40. The pipe you named is the pipe you buy.",
    stock: "from ¾″ PVC",
  },
  {
    id: "bridge",
    group: "weekend",
    section: "Weekend",
    label: "Straw Warren bridge",
    size: "4 ft",
    prompt: "4 foot bridge from plastic drinking straws",
    blurb: "Single stock, Warren truss, densified deck. Drinking straws — not a lumber aisle.",
    stock: "from drinking straws",
  },
];

export const IDEA_SECTIONS = [
  "Fitted to a hole",
  "Sit and work",
  "Hang on the wall",
  "Store",
  "Weekend",
] as const;
