/** Stress prompts from passes 1–6. Every one must keep its size line equal to the model and its cues honest. */
export const STRESS_PROMPTS = [
  "linen closet 31.5 wide 78 tall 16 deep",
  "linen cupboard in the hallway alcove 28 wide 80 tall 15 deep with 2 doors",
  "garage wall cabinet no doors 48 wide 30 tall 12 deep",
  "cedar 2x6 raised garden bed 48x24x11",
  "walnut 1x8 wall shelf with 2 tiers 30 long",
  "oak 1x10 wall shelf with 3 tiers 36 long",
  "popsicle stick coaster 4 inch",
  "craft stick bird feeder",
  "cedar bird feeder",
  "maple cat scratching post 30 tall",
  "pine dog ramp for the couch 18 high",
  "blanket chest with a lift-off lid, no lid actually, 36 wide",
  "nightstand with no drawers and 1 drawer 18 wide",
  "pine 2x4 bench 48 wide",
  "cedar 1x6 bench 60 wide",
  "bench 48x18x16",
  "2x4x8 bench",
  "bookcase 30x12x72",
  "pantry cabinet with doors in the kitchen recess 24 wide 84 tall 14 deep",
  "dresser with no drawers 36 wide",
  "bookcase with no doors 30 wide",
  "media console no doors 60 wide",
  "bathroom vanity with no doors 30 wide",
  "picnic table 6 ft cedar",
  "bathroom shelf",
  "wall shelf 30 long",
  "pine dog bed frame 36 wide",
  "cedar bunny hutch 48 wide",
  "plywood cat feeding station 24 wide",
];
