/** Stress prompts from passes 1–7. Every one must keep its size line equal to the model and its cues honest. */
export const STRESS_PROMPTS = [
  "linen closet 31.5 wide 78 tall 16 deep",
  "linen cupboard in the hallway alcove 28 wide 80 tall 15 deep with 2 doors",
  "garage wall cabinet no doors 48 wide 30 tall 12 deep",
  "cedar 2x6 raised garden bed 48x24x11",
  "walnut 1x8 wall shelf with 2 tiers 30 long",
  "oak 1x10 wall shelf with 3 tiers 36 long",
  "popsicle stick coaster 4 inch",
  "craft stick bird feeder",
  "cedar bird feeder",
  "maple cat scratching post 30 tall",
  "pine dog ramp for the couch 18 high",
  "blanket chest with a lift-off lid, no lid actually, 36 wide",
  "nightstand with no drawers and 1 drawer 18 wide",
  "pine 2x4 bench 48 wide",
  "cedar 1x6 bench 60 wide",
  "bench 48x18x16",
  "2x4x8 bench",
  "bookcase 30x12x72",
  "pantry cabinet with doors in the kitchen recess 24 wide 84 tall 14 deep",
  "dresser with no drawers 36 wide",
  "bookcase with no doors 30 wide",
  "media console no doors 60 wide",
  "bathroom vanity with no doors 30 wide",
  "picnic table 6 ft cedar",
  "bathroom shelf",
  "wall shelf 30 long",
  "pine dog bed frame 36 wide",
  "cedar bunny hutch 48 wide",
  "plywood cat feeding station 24 wide",
  "guinea pig hutch",
  "rabbit hutch 48x24x36",
  "chicken coop",
  "large dog feeding station",
  "dog feeding table",
  "walnut 1x8 wall shelf",
  "maple 1x6 floating shelf 24 long",
  "pine 1x12 wall shelf with 2 brackets",
  "broom cabinet",
  "pine cat bed 20 wide",
  "hall closet 36 wide 84 tall 24 deep",
  "cedar 2x4 potting bench 48 wide",
  "walnut 1x10 floating shelf 30 long",
  "floating shelf with lip 24 wide 6 tall",
  "popsicle stick photo frame 4x6",
  "popsicle stick picture frame 6 inch",
  "medicine cabinet 20 wide 26 tall 5 deep",
  "cat feeding station",
  "broom closet 20 wide 80 tall 14 deep",
  "maple 1x10 record console 54 wide",
  "cedar garbage bin enclosure from 2x4 for two bins",
  "Arc de Triomphe from craft sticks 12 inches tall",
  "bee hotel from scrap 1x6",
  "firewood shed from 2x4",
  "Big Ben from popsicle sticks 18 inches tall",
  "log store from 4x4 and 1x6",
  "Tower Bridge from popsicle sticks",
  "Leaning Tower of Pisa from craft sticks",
  "tool shed from 2x4",
  "coat closet 36 wide 80 tall 24 deep with a rod",
  "vanity mirror 24 wide",
  "dog crate 36 long",
  "record crate",
  "firewood rack",
  "Stanley Quencher 40 oz shelf",
  "shelf for a Yeti 20 oz tumbler",
  "TV stand 55 inch",
  "bar stool 30 tall",
  "baby gate 30 wide",
  "doll bed from popsicle sticks",
  "mirror frame 24 by 36",
  "sandbox cover 4 by 4",
  "folding table 48 by 24 36 inches high",
  "cedar planter 30 long 14 wide 12 tall",
  "PVC garden arch 4 feet wide",
  "cardboard rocket 10 wide 28 tall",
  "sawhorse 32 long",
  "shoe rack with cubbies",
  "entry bench with shoe storage",
  "firewood rack",
  "baby gate",
  "bar stool",
  "dollhouse bed",
  "32 inch tv stand",
  "dining chair",
  "workbench",
  "blanket ladder",
  "queen platform bed",
  "step stool",
  "cat tree",
  "potting bench",
  "chicken coop",
  "daybed",
  "bar stool from plywood",
  "coat rack with 5 hooks",
  "wardrobe with a rod",
  "twin loft bed",
  "window seat with cubbies",
  "mudroom bench with cubbies",
  "spice cabinet",
  "display cabinet",
  "utility cabinet",
];
